#!/usr/bin/env python3

import sys
import math

def factorize_it(n):
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            return i, n//i
    return None, None

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

fn = sys.argv[1]

try:
    with open(fn, 'r') as f:
        for oneline in f:
            n = int(oneline.strip())
            p, q = factorize_it(n)
            print("{}={}*{}".format(n, p, q))
except IOError:
    print("Error: Could not read file", fn)
    sys.exit(1)
